<# generate-dashboard.ps1 - Git dashboard data generator #>

$ErrorActionPreference = "Continue"
$RepoPath = "D:\modmangerpd\UE-Game-ModManager"
$OutputFile = Join-Path $RepoPath "dashboard-data.js"

# Fix encoding for Chinese characters in git output
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$env:LC_ALL = "C.UTF-8"

Set-Location $RepoPath

$since = (Get-Date).AddDays(-365).ToString("yyyy-MM-dd")

$commitLines = git log --all --after="$since" --pretty=format:"%H|%h|%s|%ai|%an"
$commits = @()

if ($commitLines) {
    foreach ($cline in $commitLines) {
        $cline = "$cline".Trim()
        if ($cline -match '^([0-9a-f]{40})\|(.+?)\|(.+?)\|(.+?)\|(.+)$') {
            $commits += @{
                hash      = $Matches[1]
                shortHash = $Matches[2]
                message   = $Matches[3]
                date      = $Matches[4]
                author    = $Matches[5]
                files     = @()
                additions = 0
                deletions = 0
            }
        }
    }
}

foreach ($c in $commits) {
    $numstat = git diff-tree --root --numstat --no-commit-id -r $c.hash 2>$null
    if ($numstat) {
        foreach ($fline in $numstat) {
            $fline = "$fline".Trim()
            if ($fline -match '^(\d+|-)\s+(\d+|-)\s+(.+)$') {
                $added = if ($Matches[1] -eq "-") { 0 } else { [int]$Matches[1] }
                $deleted = if ($Matches[2] -eq "-") { 0 } else { [int]$Matches[2] }
                $filePath = $Matches[3]

                $status = "modified"
                if ($added -gt 0 -and $deleted -eq 0) { $status = "added" }
                if ($added -eq 0 -and $deleted -gt 0) { $status = "deleted" }

                $c.files += @{
                    path      = $filePath
                    additions = $added
                    deletions = $deleted
                    status    = $status
                }
                $c.additions += $added
                $c.deletions += $deleted
            }
        }
    }
}

Write-Host "Parsed $($commits.Count) commits"

$dailyStats = @{}
foreach ($c in $commits) {
    $day = ("$($c.date)" -split " ")[0]
    if ($day -and $day -ne "") {
        if ($dailyStats.ContainsKey($day)) {
            $dailyStats[$day] += 1
        } else {
            $dailyStats[$day] = 1
        }
    }
}

$heatmapData = @()
foreach ($key in ($dailyStats.Keys | Sort-Object)) {
    $heatmapData += @{ date = $key; count = $dailyStats[$key] }
}

$snapshotBranches = @()
$branchPattern = 'snapshot/*'
$branches = git branch --list $branchPattern --format='%(refname:short)' 2>$null
if ($branches) {
    foreach ($bname in $branches) {
        $bname = "$bname".Trim()
        if ($bname -ne "") {
            $bdate = git log -1 --format='%ai' $bname 2>$null
            $snapshotBranches += @{ name = $bname; date = "$bdate" }
        }
    }
}

$commitsData = [System.Collections.ArrayList]@()
foreach ($c in $commits) {
    $filesArr = [System.Collections.ArrayList]@()
    foreach ($f in $c.files) {
        [void]$filesArr.Add(@{
            path      = $f.path
            additions = $f.additions
            deletions = $f.deletions
            status    = $f.status
        })
    }
    [void]$commitsData.Add(@{
        hash      = $c.hash
        shortHash = $c.shortHash
        message   = $c.message
        date      = $c.date
        author    = $c.author
        files     = $filesArr
        additions = $c.additions
        deletions = $c.deletions
    })
}

$data = @{
    generatedAt = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
    commits     = $commitsData
    heatmap     = $heatmapData
    snapshots   = $snapshotBranches
}

$json = $data | ConvertTo-Json -Depth 5 -Compress
$jsContent = "// Auto-generated by generate-dashboard.ps1" + [Environment]::NewLine + "const DASHBOARD_DATA = $json;"

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutputFile, $jsContent, $utf8NoBom)

Write-Host "Dashboard data generated: $OutputFile" -ForegroundColor Green
Write-Host "  Commits: $($commits.Count)" -ForegroundColor Cyan
Write-Host "  Snapshots: $($snapshotBranches.Count)" -ForegroundColor Cyan
