using System.Collections.Generic;

namespace UEModManager.Tests.Themes;

/// <summary>
/// 主题资源快照。由 ThemeSnapshotGenerator 生成，请勿手工编辑。
/// </summary>
public static partial class ThemeSnapshot
{
    public static readonly string[] Keys =
    {
        "SetupAccentBrush",
        "SetupAccentHoverBrush",
        "SetupAccentHoverColor",
        "SetupAccentInkBrush",
        "SetupAccentInkColor",
        "SetupBadgeBrush",
        "SetupBadgeColor",
        "SetupCloseHoverBrush",
        "SetupCloseHoverColor",
        "SetupErrorBrush",
        "SetupErrorColor",
        "SetupHoverBrush",
        "SetupHoverColor",
        "SetupIconSelectedBrush",
        "SetupIconSelectedColor",
        "SetupIconSelectedLineBrush",
        "SetupIconSelectedLineColor",
        "SetupInputBrush",
        "SetupInputColor",
        "SetupLineBrush",
        "SetupLineColor",
        "SetupMeterBrush",
        "SetupMeterColor",
        "SetupMutedBrush",
        "SetupOnCloseBrush",
        "SetupOnCloseColor",
        "SetupRadioOutlineBrush",
        "SetupRowBrush",
        "SetupRowColor",
        "SetupSecondaryBrush",
        "SetupSecondaryColor",
        "SetupSelectedBrush",
        "SetupSelectedColor",
        "SetupSelectedHoverBrush",
        "SetupSelectedHoverColor",
        "SetupSelectedLineBrush",
        "SetupSoftLineBrush",
        "SetupSoftLineColor",
        "SetupSurfaceBrush",
        "SetupSurfaceColor",
        "SetupTextBrush",
        "SetupTitleBarBrush",
        "SetupTitleBarColor",
        "SetupTrackBrush",
        "SetupTrackColor",
        "SetupWarningBrush",
        "SetupWarningColor",
        "BgBaseBrush",
        "BgBaseColor",
        "BorderColor",
        "BorderLightBrush",
        "BorderLightColor",
        "CloseHoverBrush",
        "CloseHoverColor",
        "ClosePressedBrush",
        "ClosePressedColor",
        "ConfigAmberBgBrush",
        "ConfigAmberBgColor",
        "ConfigAmberBrush",
        "ConfigAmberColor",
        "CyberBorderBrush",
        "CyberBorderlessWindow",
        "CyberCheckBox",
        "CyberCloseButton",
        "CyberComboBox",
        "CyberComboBoxToggleButton",
        "CyberCompactButton",
        "CyberContextMenu",
        "CyberDarkWindow",
        "CyberGhostButton",
        "CyberHorizontalScrollBar",
        "CyberLabel",
        "CyberListBoxItem",
        "CyberListViewItem",
        "CyberMenuItem",
        "CyberMenuItemDanger",
        "CyberMenuItemSubmenuHeader",
        "CyberMenuSeparator",
        "CyberModalWindow",
        "CyberNavItem",
        "CyberPrimaryButton",
        "CyberProgressBar",
        "CyberScrollBarHorizontalThumb",
        "CyberScrollBarThumb",
        "CyberScrollViewer",
        "CyberSecondaryButton",
        "CyberSlider",
        "CyberTextBox",
        "CyberToggleSwitch",
        "CyberToolTip",
        "CyberVerticalScrollBar",
        "CyberWindowControlButton",
        "DangerBrush",
        "DividerBrush",
        "DividerColor",
        "DropdownBgBrush",
        "DropdownBgColor",
        "DropdownBorderBrush",
        "DropdownBorderColor",
        "ImportButtonGradient",
        "InterFont",
        "ItemActiveBrush",
        "ItemActiveColor",
        "ItemHoverBrush",
        "ItemHoverColor",
        "LaunchButtonGradient",
        "ManagementTabStyle",
        "ModCyanBgBrush",
        "ModCyanBgColor",
        "OverlayBrush",
        "OverlayColor",
        "PluginPurpleBgBrush",
        "PluginPurpleBgColor",
        "PluginPurpleBrush",
        "PluginPurpleColor",
        "PrimaryBrush",
        "PrimaryColor",
        "PrimaryHoverBrush",
        "PrimaryHoverColor",
        "PrimaryLightBrush",
        "PrimaryLightColor",
        "RadiusLg",
        "RadiusMd",
        "RadiusSm",
        "StatusGreenBrush",
        "StatusGreenColor",
        "StatusOrangeBrush",
        "StatusOrangeColor",
        "StatusRedBrush",
        "StatusRedColor",
        "SurfaceBrush",
        "SurfaceColor",
        "SurfaceHoverBrush",
        "SurfaceHoverColor",
        "Text100Brush",
        "Text100Color",
        "Text200Brush",
        "Text200Color",
        "Text300Brush",
        "Text300Color",
        "Text400Brush",
        "Text400Color",
        "Text500Brush",
        "Text500Color",
        "Text600Brush",
        "Text600Color",
        "Text700Brush",
        "Text700Color",
        "TitlebarBrush",
        "TitlebarColor",
    };

    public static readonly Dictionary<string, string> Values = new()
    {
        ["SetupAccentBrush"] = "Solid #FF22D3EE @1",
        ["SetupAccentHoverBrush"] = "Solid #FF67E8F9 @1",
        ["SetupAccentHoverColor"] = "#FF67E8F9",
        ["SetupAccentInkBrush"] = "Solid #FF083344 @1",
        ["SetupAccentInkColor"] = "#FF083344",
        ["SetupBadgeBrush"] = "Solid #1322D3EE @1",
        ["SetupBadgeColor"] = "#1322D3EE",
        ["SetupCloseHoverBrush"] = "Solid #FFC42B38 @1",
        ["SetupCloseHoverColor"] = "#FFC42B38",
        ["SetupErrorBrush"] = "Solid #FFF87171 @1",
        ["SetupErrorColor"] = "#FFF87171",
        ["SetupHoverBrush"] = "Solid #FF27272B @1",
        ["SetupHoverColor"] = "#FF27272B",
        ["SetupIconSelectedBrush"] = "Solid #0922D3EE @1",
        ["SetupIconSelectedColor"] = "#0922D3EE",
        ["SetupIconSelectedLineBrush"] = "Solid #4022D3EE @1",
        ["SetupIconSelectedLineColor"] = "#4022D3EE",
        ["SetupInputBrush"] = "Solid #FF121214 @1",
        ["SetupInputColor"] = "#FF121214",
        ["SetupLineBrush"] = "Solid #FF343439 @1",
        ["SetupLineColor"] = "#FF343439",
        ["SetupMeterBrush"] = "Solid #FF73737D @1",
        ["SetupMeterColor"] = "#FF73737D",
        ["SetupMutedBrush"] = "Solid #FFA1A1AA @1",
        ["SetupOnCloseBrush"] = "Solid #FFFFFFFF @1",
        ["SetupOnCloseColor"] = "#FFFFFFFF",
        ["SetupRadioOutlineBrush"] = "Solid #FF71717A @1",
        ["SetupRowBrush"] = "Solid #FF202023 @1",
        ["SetupRowColor"] = "#FF202023",
        ["SetupSecondaryBrush"] = "Solid #FFB0B0BA @1",
        ["SetupSecondaryColor"] = "#FFB0B0BA",
        ["SetupSelectedBrush"] = "Solid #FF172C31 @1",
        ["SetupSelectedColor"] = "#FF172C31",
        ["SetupSelectedHoverBrush"] = "Solid #FF1C343A @1",
        ["SetupSelectedHoverColor"] = "#FF1C343A",
        ["SetupSelectedLineBrush"] = "Solid #FF0891B2 @1",
        ["SetupSoftLineBrush"] = "Solid #FF2C2C31 @1",
        ["SetupSoftLineColor"] = "#FF2C2C31",
        ["SetupSurfaceBrush"] = "Solid #FF18181B @1",
        ["SetupSurfaceColor"] = "#FF18181B",
        ["SetupTextBrush"] = "Solid #FFF4F4F5 @1",
        ["SetupTitleBarBrush"] = "Solid #FF161618 @1",
        ["SetupTitleBarColor"] = "#FF161618",
        ["SetupTrackBrush"] = "Solid #FF38383F @1",
        ["SetupTrackColor"] = "#FF38383F",
        ["SetupWarningBrush"] = "Solid #FFFBBF24 @1",
        ["SetupWarningColor"] = "#FFFBBF24",
        ["BgBaseBrush"] = "Solid #FF030303 @1",
        ["BgBaseColor"] = "#FF030303",
        ["BorderColor"] = "#FF27272A",
        ["BorderLightBrush"] = "Solid #FF3F3F46 @1",
        ["BorderLightColor"] = "#FF3F3F46",
        ["CloseHoverBrush"] = "Solid #FFDC2626 @1",
        ["CloseHoverColor"] = "#FFDC2626",
        ["ClosePressedBrush"] = "Solid #FFB91C1C @1",
        ["ClosePressedColor"] = "#FFB91C1C",
        ["ConfigAmberBgBrush"] = "Solid #20F59E0B @1",
        ["ConfigAmberBgColor"] = "#20F59E0B",
        ["ConfigAmberBrush"] = "Solid #FFF59E0B @1",
        ["ConfigAmberColor"] = "#FFF59E0B",
        ["CyberBorderBrush"] = "Solid #FF27272A @1",
        ["CyberBorderlessWindow"] = "Style<Window> setters=11 triggers=0",
        ["CyberCheckBox"] = "Style<CheckBox> setters=5 triggers=0",
        ["CyberCloseButton"] = "Style<Button> setters=6 triggers=0",
        ["CyberComboBox"] = "Style<ComboBox> setters=11 triggers=0",
        ["CyberComboBoxToggleButton"] = "Style<ToggleButton> setters=5 triggers=0",
        ["CyberCompactButton"] = "Style<Button> setters=9 triggers=0",
        ["CyberContextMenu"] = "Style<ContextMenu> setters=10 triggers=0",
        ["CyberDarkWindow"] = "Style<Window> setters=10 triggers=0",
        ["CyberGhostButton"] = "Style<Button> setters=8 triggers=0",
        ["CyberHorizontalScrollBar"] = "Style<ScrollBar> setters=4 triggers=0",
        ["CyberLabel"] = "Style<TextBlock> setters=4 triggers=0",
        ["CyberListBoxItem"] = "Style<ListBoxItem> setters=7 triggers=0",
        ["CyberListViewItem"] = "Style<ListViewItem> setters=7 triggers=0",
        ["CyberMenuItem"] = "Style<MenuItem> setters=7 triggers=0",
        ["CyberMenuItemDanger"] = "Style<MenuItem> setters=1 triggers=0",
        ["CyberMenuItemSubmenuHeader"] = "Style<MenuItem> setters=7 triggers=1",
        ["CyberMenuSeparator"] = "Style<Separator> setters=3 triggers=0",
        ["CyberModalWindow"] = "Style<Window> setters=10 triggers=0",
        ["CyberNavItem"] = "Style<RadioButton> setters=6 triggers=0",
        ["CyberPrimaryButton"] = "Style<Button> setters=9 triggers=0",
        ["CyberProgressBar"] = "Style<ProgressBar> setters=4 triggers=0",
        ["CyberScrollBarHorizontalThumb"] = "Style<Thumb> setters=1 triggers=0",
        ["CyberScrollBarThumb"] = "Style<Thumb> setters=1 triggers=0",
        ["CyberScrollViewer"] = "Style<ScrollViewer> setters=1 triggers=0",
        ["CyberSecondaryButton"] = "Style<Button> setters=8 triggers=0",
        ["CyberSlider"] = "Style<Slider> setters=4 triggers=0",
        ["CyberTextBox"] = "Style<TextBox> setters=12 triggers=0",
        ["CyberToggleSwitch"] = "Style<CheckBox> setters=2 triggers=0",
        ["CyberToolTip"] = "Style<ToolTip> setters=8 triggers=0",
        ["CyberVerticalScrollBar"] = "Style<ScrollBar> setters=4 triggers=0",
        ["CyberWindowControlButton"] = "Style<Button> setters=6 triggers=0",
        ["DangerBrush"] = "Solid #FFEF4444 @1",
        ["DividerBrush"] = "Solid #27272A99 @1",
        ["DividerColor"] = "#27272A99",
        ["DropdownBgBrush"] = "Solid #FF0F0F11 @1",
        ["DropdownBgColor"] = "#FF0F0F11",
        ["DropdownBorderBrush"] = "Solid #FF3F3F46 @1",
        ["DropdownBorderColor"] = "#FF3F3F46",
        ["ImportButtonGradient"] = "Linear #FF06B6D4@0,#FF0891B2@1 0,0->1,1",
        ["InterFont"] = "Font pack://application:,,,/Fonts/#Source Han Sans SC, Microsoft YaHei UI, Segoe UI",
        ["ItemActiveBrush"] = "Solid #FF1A1A1D @1",
        ["ItemActiveColor"] = "#FF1A1A1D",
        ["ItemHoverBrush"] = "Solid #FF1A1A1D @1",
        ["ItemHoverColor"] = "#FF1A1A1D",
        ["LaunchButtonGradient"] = "Linear #FF10B981@0,#FF059669@1 0,0->1,1",
        ["ManagementTabStyle"] = "Style<Button> setters=9 triggers=1",
        ["ModCyanBgBrush"] = "Solid #2006B6D4 @1",
        ["ModCyanBgColor"] = "#2006B6D4",
        ["OverlayBrush"] = "Solid #CC000000 @1",
        ["OverlayColor"] = "#CC000000",
        ["PluginPurpleBgBrush"] = "Solid #20A855F7 @1",
        ["PluginPurpleBgColor"] = "#20A855F7",
        ["PluginPurpleBrush"] = "Solid #FFA855F7 @1",
        ["PluginPurpleColor"] = "#FFA855F7",
        ["PrimaryBrush"] = "Solid #FF06B6D4 @1",
        ["PrimaryColor"] = "#FF06B6D4",
        ["PrimaryHoverBrush"] = "Solid #FF0891B2 @1",
        ["PrimaryHoverColor"] = "#FF0891B2",
        ["PrimaryLightBrush"] = "Solid #FF22D3EE @1",
        ["PrimaryLightColor"] = "#FF22D3EE",
        ["RadiusLg"] = "Radius 16,16,16,16",
        ["RadiusMd"] = "Radius 12,12,12,12",
        ["RadiusSm"] = "Radius 8,8,8,8",
        ["StatusGreenBrush"] = "Solid #FF22C55E @1",
        ["StatusGreenColor"] = "#FF22C55E",
        ["StatusOrangeBrush"] = "Solid #FFF97316 @1",
        ["StatusOrangeColor"] = "#FFF97316",
        ["StatusRedBrush"] = "Solid #FFEF4444 @1",
        ["StatusRedColor"] = "#FFEF4444",
        ["SurfaceBrush"] = "Solid #FF0F0F11 @1",
        ["SurfaceColor"] = "#FF0F0F11",
        ["SurfaceHoverBrush"] = "Solid #FF1A1A1D @1",
        ["SurfaceHoverColor"] = "#FF1A1A1D",
        ["Text100Brush"] = "Solid #FFF4F4F5 @1",
        ["Text100Color"] = "#FFF4F4F5",
        ["Text200Brush"] = "Solid #FFE4E4E7 @1",
        ["Text200Color"] = "#FFE4E4E7",
        ["Text300Brush"] = "Solid #FFD4D4D8 @1",
        ["Text300Color"] = "#FFD4D4D8",
        ["Text400Brush"] = "Solid #FFA1A1AA @1",
        ["Text400Color"] = "#FFA1A1AA",
        ["Text500Brush"] = "Solid #FF71717A @1",
        ["Text500Color"] = "#FF71717A",
        ["Text600Brush"] = "Solid #FF52525B @1",
        ["Text600Color"] = "#FF52525B",
        ["Text700Brush"] = "Solid #FF3F3F46 @1",
        ["Text700Color"] = "#FF3F3F46",
        ["TitlebarBrush"] = "Solid #FF0A0A0C @1",
        ["TitlebarColor"] = "#FF0A0A0C",
    };
}
