using System.Collections.Generic;

namespace UEModManager.Tests.Themes;

/// <summary>
/// 主题资源快照。由 ThemeSnapshotGenerator 生成，请勿手工编辑。
///
/// 基线取自 2026-07-27 主题分层重构前的实际运行结果，122 个 key。
/// 重构后只有 10 个值发生变化，全部是 5 个 "Bg" 半透明色标及其派生画刷：
/// 它们原先写成 #RRGGBBAA，被 WPF 按 #AARRGGBB 解析成几乎全透明的错色。
/// 修正是安全的——修正前这 10 个 key 在 Themes 之外零引用，没有任何消费者，
/// 所以不改变任何一个像素；修正后 ValueConverters 才能引用它们并保持原有观感。
/// 其余 112 个 key 逐字节未变。
/// </summary>
public static partial class ThemeSnapshot
{
    public static readonly string[] Keys =
    {
        "BgBaseBrush",
        "BgBaseColor",
        "BorderColor",
        "BorderLightBrush",
        "BorderLightColor",
        "CloseHoverBrush",
        "CloseHoverColor",
        "ClosePressedBrush",
        "ClosePressedColor",
        "ConfigAmberBgBrush",
        "ConfigAmberBgColor",
        "ConfigAmberBrush",
        "ConfigAmberColor",
        "CyberBorderBrush",
        "CyberBorderlessWindow",
        "CyberCheckBox",
        "CyberCloseButton",
        "CyberComboBox",
        "CyberComboBoxToggleButton",
        "CyberCompactButton",
        "CyberContextMenu",
        "CyberDangerButton",
        "CyberDarkWindow",
        "CyberExpander",
        "CyberGhostButton",
        "CyberGroupBox",
        "CyberHorizontalScrollBar",
        "CyberLabel",
        "CyberLinkButton",
        "CyberListBoxItem",
        "CyberListViewItem",
        "CyberMenuItem",
        "CyberMenuItemDanger",
        "CyberMenuSeparator",
        "CyberModalWindow",
        "CyberNavItem",
        "CyberPasswordBox",
        "CyberPrimaryButton",
        "CyberProgressBar",
        "CyberScrollBarHorizontalThumb",
        "CyberScrollBarThumb",
        "CyberScrollViewer",
        "CyberSecondaryButton",
        "CyberSettingItem",
        "CyberSlider",
        "CyberTabControl",
        "CyberTabItem",
        "CyberTextBox",
        "CyberToggleSwitch",
        "CyberToolTip",
        "CyberVerticalScrollBar",
        "CyberWindowControlButton",
        "DangerBrush",
        "DividerBrush",
        "DividerColor",
        "DropdownBgBrush",
        "DropdownBgColor",
        "DropdownBorderBrush",
        "DropdownBorderColor",
        "ErrorBrush",
        "ImportButtonGradient",
        "InterFont",
        "ItemActiveBorderBrush",
        "ItemActiveBorderColor",
        "ItemActiveBrush",
        "ItemActiveColor",
        "ItemHoverBrush",
        "ItemHoverColor",
        "LaunchButtonGradient",
        "LoserRedBgBrush",
        "LoserRedBgColor",
        "ManagementTabStyle",
        "ModCyanBgBrush",
        "ModCyanBgColor",
        "OverlayBrush",
        "OverlayColor",
        "PluginPurpleBgBrush",
        "PluginPurpleBgColor",
        "PluginPurpleBrush",
        "PluginPurpleColor",
        "PrimaryBrush",
        "PrimaryColor",
        "PrimaryGlowBrush",
        "PrimaryGlowColor",
        "PrimaryHoverBrush",
        "PrimaryHoverColor",
        "PrimaryLightBrush",
        "PrimaryLightColor",
        "RadiusLg",
        "RadiusMd",
        "RadiusSm",
        "RadiusXl",
        "StatusGreenBrush",
        "StatusGreenColor",
        "StatusOrangeBrush",
        "StatusOrangeColor",
        "StatusRedBrush",
        "StatusRedColor",
        "SuccessBrush",
        "SurfaceBrush",
        "SurfaceColor",
        "SurfaceHoverBrush",
        "SurfaceHoverColor",
        "Text100Brush",
        "Text100Color",
        "Text200Brush",
        "Text200Color",
        "Text300Brush",
        "Text300Color",
        "Text400Brush",
        "Text400Color",
        "Text500Brush",
        "Text500Color",
        "Text600Brush",
        "Text600Color",
        "Text700Brush",
        "Text700Color",
        "TitlebarBrush",
        "TitlebarColor",
        "WarningBrush",
        "WinnerGreenBgBrush",
        "WinnerGreenBgColor",
    };

    public static readonly Dictionary<string, string> Values = new()
    {
        ["BgBaseBrush"] = "Solid #FF030303 @1",
        ["BgBaseColor"] = "#FF030303",
        ["BorderColor"] = "#FF27272A",
        ["BorderLightBrush"] = "Solid #FF3F3F46 @1",
        ["BorderLightColor"] = "#FF3F3F46",
        ["CloseHoverBrush"] = "Solid #FFDC2626 @1",
        ["CloseHoverColor"] = "#FFDC2626",
        ["ClosePressedBrush"] = "Solid #FFB91C1C @1",
        ["ClosePressedColor"] = "#FFB91C1C",
        ["ConfigAmberBgBrush"] = "Solid #20F59E0B @1",
        ["ConfigAmberBgColor"] = "#20F59E0B",
        ["ConfigAmberBrush"] = "Solid #FFF59E0B @1",
        ["ConfigAmberColor"] = "#FFF59E0B",
        ["CyberBorderBrush"] = "Solid #FF27272A @1",
        ["CyberBorderlessWindow"] = "Style<Window> setters=11 triggers=0",
        ["CyberCheckBox"] = "Style<CheckBox> setters=5 triggers=0",
        ["CyberCloseButton"] = "Style<Button> setters=6 triggers=0",
        ["CyberComboBox"] = "Style<ComboBox> setters=11 triggers=0",
        ["CyberComboBoxToggleButton"] = "Style<ToggleButton> setters=5 triggers=0",
        ["CyberCompactButton"] = "Style<Button> setters=9 triggers=0",
        ["CyberContextMenu"] = "Style<ContextMenu> setters=10 triggers=0",
        ["CyberDangerButton"] = "Style<Button> setters=9 triggers=0",
        ["CyberDarkWindow"] = "Style<Window> setters=10 triggers=0",
        ["CyberExpander"] = "Style<Expander> setters=8 triggers=0",
        ["CyberGhostButton"] = "Style<Button> setters=8 triggers=0",
        ["CyberGroupBox"] = "Style<GroupBox> setters=7 triggers=0",
        ["CyberHorizontalScrollBar"] = "Style<ScrollBar> setters=4 triggers=0",
        ["CyberLabel"] = "Style<TextBlock> setters=4 triggers=0",
        ["CyberLinkButton"] = "Style<Button> setters=8 triggers=0",
        ["CyberListBoxItem"] = "Style<ListBoxItem> setters=7 triggers=0",
        ["CyberListViewItem"] = "Style<ListViewItem> setters=7 triggers=0",
        ["CyberMenuItem"] = "Style<MenuItem> setters=7 triggers=0",
        ["CyberMenuItemDanger"] = "Style<MenuItem> setters=1 triggers=0",
        ["CyberMenuSeparator"] = "Style<Separator> setters=3 triggers=0",
        ["CyberModalWindow"] = "Style<Window> setters=10 triggers=0",
        ["CyberNavItem"] = "Style<RadioButton> setters=6 triggers=0",
        ["CyberPasswordBox"] = "Style<PasswordBox> setters=12 triggers=0",
        ["CyberPrimaryButton"] = "Style<Button> setters=9 triggers=0",
        ["CyberProgressBar"] = "Style<ProgressBar> setters=4 triggers=0",
        ["CyberScrollBarHorizontalThumb"] = "Style<Thumb> setters=1 triggers=0",
        ["CyberScrollBarThumb"] = "Style<Thumb> setters=1 triggers=0",
        ["CyberScrollViewer"] = "Style<ScrollViewer> setters=1 triggers=0",
        ["CyberSecondaryButton"] = "Style<Button> setters=8 triggers=0",
        ["CyberSettingItem"] = "Style<Border> setters=3 triggers=0",
        ["CyberSlider"] = "Style<Slider> setters=4 triggers=0",
        ["CyberTabControl"] = "Style<TabControl> setters=3 triggers=0",
        ["CyberTabItem"] = "Style<TabItem> setters=7 triggers=0",
        ["CyberTextBox"] = "Style<TextBox> setters=12 triggers=0",
        ["CyberToggleSwitch"] = "Style<CheckBox> setters=2 triggers=0",
        ["CyberToolTip"] = "Style<ToolTip> setters=8 triggers=0",
        ["CyberVerticalScrollBar"] = "Style<ScrollBar> setters=4 triggers=0",
        ["CyberWindowControlButton"] = "Style<Button> setters=6 triggers=0",
        ["DangerBrush"] = "Solid #FFEF4444 @1",
        ["DividerBrush"] = "Solid #27272A99 @1",
        ["DividerColor"] = "#27272A99",
        ["DropdownBgBrush"] = "Solid #FF0F0F11 @1",
        ["DropdownBgColor"] = "#FF0F0F11",
        ["DropdownBorderBrush"] = "Solid #FF3F3F46 @1",
        ["DropdownBorderColor"] = "#FF3F3F46",
        ["ErrorBrush"] = "Solid #FFEF4444 @1",
        ["ImportButtonGradient"] = "Linear #FF06B6D4@0,#FF0891B2@1 0,0->1,1",
        ["InterFont"] = "Font pack://application:,,,/Fonts/#Source Han Sans SC, Microsoft YaHei UI, Segoe UI",
        ["ItemActiveBorderBrush"] = "Solid #27272A80 @1",
        ["ItemActiveBorderColor"] = "#27272A80",
        ["ItemActiveBrush"] = "Solid #FF1A1A1D @1",
        ["ItemActiveColor"] = "#FF1A1A1D",
        ["ItemHoverBrush"] = "Solid #FF1A1A1D @1",
        ["ItemHoverColor"] = "#FF1A1A1D",
        ["LaunchButtonGradient"] = "Linear #FF10B981@0,#FF059669@1 0,0->1,1",
        ["LoserRedBgBrush"] = "Solid #18EF4444 @1",
        ["LoserRedBgColor"] = "#18EF4444",
        ["ManagementTabStyle"] = "Style<Button> setters=9 triggers=1",
        ["ModCyanBgBrush"] = "Solid #2006B6D4 @1",
        ["ModCyanBgColor"] = "#2006B6D4",
        ["OverlayBrush"] = "Solid #CC000000 @1",
        ["OverlayColor"] = "#CC000000",
        ["PluginPurpleBgBrush"] = "Solid #20A855F7 @1",
        ["PluginPurpleBgColor"] = "#20A855F7",
        ["PluginPurpleBrush"] = "Solid #FFA855F7 @1",
        ["PluginPurpleColor"] = "#FFA855F7",
        ["PrimaryBrush"] = "Solid #FF06B6D4 @1",
        ["PrimaryColor"] = "#FF06B6D4",
        ["PrimaryGlowBrush"] = "Solid #06B6D440 @1",
        ["PrimaryGlowColor"] = "#06B6D440",
        ["PrimaryHoverBrush"] = "Solid #FF0891B2 @1",
        ["PrimaryHoverColor"] = "#FF0891B2",
        ["PrimaryLightBrush"] = "Solid #FF22D3EE @1",
        ["PrimaryLightColor"] = "#FF22D3EE",
        ["RadiusLg"] = "Radius 16,16,16,16",
        ["RadiusMd"] = "Radius 12,12,12,12",
        ["RadiusSm"] = "Radius 8,8,8,8",
        ["RadiusXl"] = "Radius 20,20,20,20",
        ["StatusGreenBrush"] = "Solid #FF22C55E @1",
        ["StatusGreenColor"] = "#FF22C55E",
        ["StatusOrangeBrush"] = "Solid #FFF97316 @1",
        ["StatusOrangeColor"] = "#FFF97316",
        ["StatusRedBrush"] = "Solid #FFEF4444 @1",
        ["StatusRedColor"] = "#FFEF4444",
        ["SuccessBrush"] = "Solid #FF22C55E @1",
        ["SurfaceBrush"] = "Solid #FF0F0F11 @1",
        ["SurfaceColor"] = "#FF0F0F11",
        ["SurfaceHoverBrush"] = "Solid #FF1A1A1D @1",
        ["SurfaceHoverColor"] = "#FF1A1A1D",
        ["Text100Brush"] = "Solid #FFF4F4F5 @1",
        ["Text100Color"] = "#FFF4F4F5",
        ["Text200Brush"] = "Solid #FFE4E4E7 @1",
        ["Text200Color"] = "#FFE4E4E7",
        ["Text300Brush"] = "Solid #FFD4D4D8 @1",
        ["Text300Color"] = "#FFD4D4D8",
        ["Text400Brush"] = "Solid #FFA1A1AA @1",
        ["Text400Color"] = "#FFA1A1AA",
        ["Text500Brush"] = "Solid #FF71717A @1",
        ["Text500Color"] = "#FF71717A",
        ["Text600Brush"] = "Solid #FF52525B @1",
        ["Text600Color"] = "#FF52525B",
        ["Text700Brush"] = "Solid #FF3F3F46 @1",
        ["Text700Color"] = "#FF3F3F46",
        ["TitlebarBrush"] = "Solid #FF0A0A0C @1",
        ["TitlebarColor"] = "#FF0A0A0C",
        ["WarningBrush"] = "Solid #FFF97316 @1",
        ["WinnerGreenBgBrush"] = "Solid #1822C55E @1",
        ["WinnerGreenBgColor"] = "#1822C55E",
    };
}
